apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # namespace: default
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: omarkataa/app3:latest
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: app1
  # namespace: default
spec:
  type: LoadBalancer
  selector:
    app: app1
  ports:
  - port: 9000
    targetPort: 80
